{
statusCode:0,
productList: [{
                productName: '产品AA',
                icon: 'img/1.jpg',
                isShow:true
            },{
                productName: '产品BB',
                icon: 'img/2.jpg',
                isShow:false
            },{
                productName: '产品CC',
                icon: 'img/3.jpg',
                isShow:false
            },{
                productName: '产品DD',
                icon: 'img/4.jpg',
                isShow:true
            },{
                productName: '产品EE',
                icon: 'img/5.jpg',
                isShow:true
            }]
}